table Fact
	lineageTag: 616005fd-9e09-4f2a-ad83-165711332d18

	column SUM_Measure_1
		dataType: int64
		formatString: 0
		lineageTag: c178d5a1-2e73-4e54-a478-7a8e1809c3e8
		summarizeBy: sum
		sourceColumn: SUM_Measure_1

		annotation SummarizationSetBy = Automatic

	column SUM_Measure_2
		dataType: int64
		formatString: 0
		lineageTag: 9a3a3018-a99d-497b-ad62-7cb0bcebd23d
		summarizeBy: sum
		sourceColumn: SUM_Measure_2

		annotation SummarizationSetBy = Automatic

	column CNT_Measure_1
		dataType: int64
		formatString: 0
		lineageTag: 50475eca-5241-4483-ada1-7816a5c1d7e8
		summarizeBy: sum
		sourceColumn: CNT_Measure_1

		annotation SummarizationSetBy = Automatic

	column AVG_Measure_1
		dataType: double
		lineageTag: 552928d2-3d2f-4f7a-8652-7bb4f19a831c
		summarizeBy: sum
		sourceColumn: AVG_Measure_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Key_Dim_1
		dataType: string
		lineageTag: 5b017b4b-0714-44b5-b133-8208deeb08e1
		summarizeBy: none
		sourceColumn: Key_Dim_1

		annotation SummarizationSetBy = Automatic

	column Key_Dim_2
		dataType: string
		lineageTag: 5e157ba5-c804-4e35-b0e5-fa4e4fd66404
		summarizeBy: none
		sourceColumn: Key_Dim_2

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: 00b358c6-5ec0-4855-8376-5820fcc4bc36
		summarizeBy: none
		sourceColumn: DateKey

		variation Variation
			isDefault
			relationship: 5e8e6455-5605-413c-ba4b-a5fbad25a1b1
			defaultHierarchy: LocalDateTable_d34d2e7a-ca13-4c3e-8d45-83e895bba98b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Admin\Downloads\poc_dummy_data.csv"),[Delimiter=",", Columns=7, Encoding=932, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SUM_Measure_1", Int64.Type}, {"SUM_Measure_2", Int64.Type}, {"CNT_Measure_1", Int64.Type}, {"AVG_Measure_1", type number}, {"Key_Dim_1", type text}, {"Key_Dim_2", type text}, {"DateKey", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

